print('   |   |')
    # print('-----------')
    # print('   |   |')
    # print('   |   |')
    # print(' ' + board[4] + ' | ' + board[5] + ' | ' + board[6])
    # print('   |   |')
    # print('-----------')
    # print('   |   |')
    # print(' ' + board[1] + ' | ' + board[2] + ' | ' + board[3])
    # print('   |   |')
